### ISSUE TITLE
не видит Xiaomi Gateway v3

### ISSUE THREAD

**Issue by StrangePers** [sergejey/majordomo-xiaomihome#1]
Все перепробовал - не видит Xiaomi Gateway 3. При этом Gateway переведен в режим отладки и его порт 9898 открыт. Проверял через nmap. Аналогичный модуль в HomeAssistant буквально наднях автор пофиксил, добавив возможность указывать в настройках IP адрес шлюза. Поиск бродкастов - не работает... В Home Assistant у меня заработало с фиксами автора, но к нему душа не лежит совсем :( Хочется majordomo. Оно роднее :) 
P.S. OS Windows 10.

**Comment by sergejey** [comment]
Я добавил возможность в настройках указывать IP-адрес шлюза и IP-адрес интерфейса для слушания бродкастов (если их несколько). Попробуйте пожалуйста и дайте знать поменялось ли что-то.

**Comment by StrangePers** [comment]
Попробовал разные варианты и прописывать IP шлюза, прописывать в адрес интерфейса 0.0.0.0 и оставлять пустым - не работает :( 
Причем если пустым оставлять адрес интерфейса, то ошибка на socket bind о невозможности забиндить пустой адрес "".
Фиксы в homeassistant в ветке no-discovery https://github.com/syssi/PyXiaomiGateway/tree/feature/no-discovery
https://github.com/home-assistant/home-assistant/commit/94dcf36d7cde9a55275e23f1a741cb742b105b57

**Comment by StrangePers** [comment]
При этом он писал на форуме, что discovery не работает сейчас и нужно указывать полностью адрес, мак, ключ для Gateway. Надеюсь это поможет.

**Comment by sergejey** [comment]
У меня с пустым адресом интерфейса всё корректно работает -- биндится на 0.0.0.0. Можете повторить тест и показать точные настройи? не могу добиться ошибки с пустым адресом интерфейса.

Что касается "не видит", хочу всё же уточнить -- не приходят данные от гейта (и подключенных устройств) или не получается им управлять? Дело в том, что в коде на py я вообще не нашёл ничего, что бы влияло на приём событий. Для отправки да, можно вручную прописать, но вот с приёмом как это связано...

**Comment by palacex** [comment]
Суть та же, что и у StrangePers.
Устройство: Xiaomi GateWay (lumi.gateway.v3) не отображается в интерфейсе. 

Проблему решил путём раскомментирования 93 строчки в файле цикла.
https://github.com/sergejey/majordomo-xiaomihome/blob/78a93824a99e3f4a3d690479a4f66c225ace169a/scripts/cycle_xiaomihome.php#L93

После этого, устройство отобразилось в админке.

**Comment by sergejey** [comment]
Решение с раскомментированием странное и оно скорее говорит о другой проблеме. В 91-й строке идёт http-запрос, который как раз заменяет processMessage, точнее делает его более безопасным для цикла (чтобы цикл не упал если вдруг какой неправильный пользовательский код исполнится). Если этот запрос не проходит, то, как вариант, попробовать заменить get_headers на getURLBackground или getURL

**Comment by palacex** [comment]
В настоящий момент решение не странное, а единственное рабочее.
getURLBackground и getURL также не работают.

**Comment by sergejey** [comment]
Я потому и говорю, что оно странное, что должно работать предложенными способами, а если не работает, то это признак проблемы с конфигурацией системы в целом и могут быть неожиданные ошибки в других местах. Проверьте к какой ссылке идёт обращение из get_headers, может быть она не правильная и из-за этого не доходят события. BASE_URL может быть некорректный например.

**Comment by palacex** [comment]
Проблема решена.
У меня мажордом доступен по доменному адресу, а не по IP и в config.php HOME_NETWORK указана подсеть 192.168.0.*, а у меня другая. 
Так что все запросы модуля отваливались из-за того что требовалась авторизация.
Поправил настройки в /etc/hosts и config.php и всё заработало.

**Comment by sergejey** [comment]
Воот, так-то лучше :)
