### ISSUE TITLE
В коде необъявленная переменная

### ISSUE THREAD

**Issue by fsa** [sergejey/majordomo-xiaomihome#4]
В исходном коде xiaomihome.class.php в 157 строке странная переменная, которая не инициализирована перед использованием:
               $device['ID'] = SQLInsert('xidevices', $device_type);
Судя по всему тут должно быть указано $device вместо $device_type, т.к. этот код создаёт устройство, если оно не было найдено. По логике после создания он получает ID и присваивает новый ключ этому же массиву.

**Comment by sergejey** [comment]
да, странно, что эта ошибка так давно висит. иправлено.
