### ISSUE TITLE
img

### ISSUE THREAD

**Issue by kotovmaksim** [sergejey/majordomo-xiaomihome#9]
img src="../templates/xiaomihome/img/[#TYPE#].png" height="40px" onerror="this.src='../templates/xiaomihome/img/unknown.png'"

мне кажется вы забыли закинуть картинки в папку /xiaomihome/img/ для посл. обновления :)

**Comment by skysilver-lab** [comment]
Какие именно? Вроде все на месте  https://github.com/sergejey/majordomo-xiaomihome/tree/master/templates/xiaomihome/img

**Comment by kotovmaksim** [comment]
Я еще не обновлял модуль, но судя по коду должны быть картинки success.png, warning.png и danger.png

        $out['POWER'] = $battery['VALUE'];
        $out['POWER_WARNING'] = "success";
        if ($out['POWER']<= 40)
           $out['POWER_WARNING'] = "warning";
        if ($out['POWER']<= 20)
           $out['POWER_WARNING'] = "danger";

**Comment by kotovmaksim** [comment]
а нет, все ок
извиняюсь, не внимательно смотрел
